### ISSUE TITLE
Remove Team Number From Team Registration > Team Creation. Make It Auto Incremental

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#13]
If we already have Auto Incremental field, use that field instead. In that case there's no need to use Team Number field.

**Comment by snowbreeze** [comment]
Done

**Comment by krishnandusarkar** [comment]
On Team Creation it's throwing 500 Error from functions.php. Testing Blocked.

**Comment by debasishbanerjee** [comment]
Done.
Test again and update

**Comment by krishnandusarkar** [comment]
Even though the team gets created successfully, but the message reads "Oops Something Went Wrong."

Reopening.

**Comment by krishnandusarkar** [comment]
Team Number is still there in Update.

**Comment by debasishbanerjee** [comment]
Done.Test and Update

**Comment by krishnandusarkar** [comment]
Working Fine,
