### ISSUE TITLE
Update And Cancel Button for Edit

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#14]
Across all the edit pages, there should be one button Update (green) and Cancel (grey) which should take to the entry page.

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
This needs to be done on all pages. Testing of this feature is blocked, as Edit functionality cannot be reached for all pages.

**Comment by krishnandusarkar** [comment]
Not Working For Below Pages

update_team_member.php

update_assignment.php - Here only Cancel button is needed. As editing is limited here to Unassign.

update_booth.php

update_questions.php is broken. Throwing 500 Error. Testing Blocked.

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine.
