### ISSUE TITLE
Separate Exhibitor Creation and Exhibitor Summary into two submenus under 'Exhibitors'

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#19]
Promote the current "Exhibitor Creation" to a submenu under "Exhibitors".  Change the name to "Exhibitor Registration"

Promote the current "Exhibitor Summary" to a submenu under "Exhibitors".  Change the name to "Exhibitor Summary"

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine
