### ISSUE TITLE
Change The Title To "UPDATE EXHIBITOR REGISTRATION" For Exhibitor Edit

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#20]

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
No way to edit exhibitors. Testing of this enhancement is blocked.

![image](https://cloud.githubusercontent.com/assets/3623328/17505110/84f67930-5e1c-11e6-9fd0-79bcfe35f07c.png)

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine.
