### ISSUE TITLE
Fix jqGrid Issues

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#3]
1. Make the grid responsive
2. Change the Edit href's to read "Edit" instead of jumbled ID's
3. Shift the Edit column to the end
4. Add a checkbox column with the header "Delete" in the front of all the rows
5. Add a "Delete" button at the end of the grid on the right hand side.
6. The delete should take a confirmation message before deleting the selected rows.

**Comment by snowbreeze** [comment]
Not relevant any more

**Comment by snowbreeze** [comment]
Done

**Comment by krishnandusarkar** [comment]
Removing From Issues List.
