### ISSUE TITLE
SPE Grid Partially Working / Broken

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#32]
I think you copied over the participants summary over all pages. Now Team Assignment, Exhibitor Summary all shows the same Participants Summary grid.

Either keep as it was if it cannot be completed within 16th, else fix the thing.

Because if you are updating an feature, it cannot be shared as partially working / broken for review.

So either update it completely else keep as it was in that case I'll say we are still working on it.

**Comment by snowbreeze** [comment]
Fixed. Done

**Comment by krishnandusarkar** [comment]
Working Fine.
