### ISSUE TITLE
Video Questions

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#33]
We have QuestionImage (Long Blob) and ImageType (Varchar) in Questions Table to handle the current Image upload scenario.

We store the Image Blob in Question Image field and the type of the image (i.e. image/jpeg, image/png etc.) in ImageType field. Later we use this field to render the image in it's correct format at Web App, Android and iOS.

We'll reuse the same fields for Video. Please note that either Image or Video can be uploaded for a particular question.

Reference for storing video as a long blob. 
http://stackoverflow.com/questions/21255954/insert-video-in-database

**Comment by snowbreeze** [comment]
Implemented

**Comment by krishnandusarkar** [comment]
Testing Blocked due to #41

**Comment by krishnandusarkar** [comment]
Video Questions Upload on Question Creation is working fine. Couldn't test it in Update as Questions Update is throwing Error 500.

**Comment by krishnandusarkar** [comment]
Working Fine.
