### ISSUE TITLE
Delete Issues

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#34]
**Participant Registration :** Perfectly Okay

**Team Registration :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Team Assignment Summary :** Delete seems to do nothing. Remove delete functionality, it's not needed.

**Pre Race Summary :** Edit seems to do nothing. Remove Edit, it's not needed. Rename Delete button to Uncheck.

**Exhibitor Summary :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Category Summary :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Difficulty Level Summary :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Category Sponsors Summary :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Questions Summary :** Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

**Results :** Remove Delete. Delete functionality not needed here.

**Global :** Remove "* To Edit & Delete Please Click On The MemberID In The Edit Column." text.

**Comment by krishnandusarkar** [comment]
NOTE : On All Delete Functionality, please include a confirmation message "Are you sure want to delete the selected rows?" before deleting.

**Comment by krishnandusarkar** [comment]
On Category Summary Search box is not aligned to right like grids in other pages.

**Comment by krishnandusarkar** [comment]
Below features still not working...

Team Assignment Summary : Delete seems to do nothing. Remove delete functionality, it's not needed.

Pre Race Summary : Delete not needed here. Remove delete functionality.

Questions Summary : Remove Row Wise Delete. Only Multi Delete via Checkbox will be there.

Results : Remove Delete. Delete functionality not needed here.

Global : Remove "* To Edit & Delete Please Click On The MemberID In The Edit Column." text.

**Comment by debasishbanerjee** [comment]
Done.
Test all the above issues and update.

**Comment by krishnandusarkar** [comment]
Working Fine.
