### ISSUE TITLE
Ability to upload/change the SPE logo in race control the one above menu

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#42]

**Comment by debasishbanerjee** [comment]
Done

**Comment by snowbreeze** [comment]
@krishnandusarkar i thnk in server, php file cant overwrite the file, some permission issue

**Comment by snowbreeze** [comment]
@krishnandusarkar need to check if php has permission to modify file.

**Comment by snowbreeze** [comment]
This is working locally but not on server

**Comment by krishnandusarkar** [comment]
@snowbreeze @debasishbanerjee Now I don't see any error, but I also don't see the updated logo. Is this still a issue on server end?

**Comment by krishnandusarkar** [comment]
Working Fine.
