### ISSUE TITLE
Footnote for Text Questions

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#46]
On Question Creation, when selecting Text under Question Type, the Answer Options Text Box and a Add button below it should be followed by a footnote saying "Enter all words that are valid answers by clicking Add Button such as :  Inline, Online, In line, On line, In-Line, In-line, On-Line, On-line, etc."

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Fine on Question Creation. Can't test on Edit as Question Edit is throwing Error 500.

**Comment by krishnandusarkar** [comment]
Working Fine.
