### ISSUE TITLE
Categorize Race Setup Options

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#48]
- General Set Up (Maximum Number Of Stations, Number Of Categories Of Questions, Number Of Categories Displayed In The APP, Number Of Difficulty Levels, Number Of Questions Per Difficulty Level)
- Multiple Choice Questions (Multiple Choice Questions, Multiple Choice Embedded Image, Multiple Choice Answer Options, Multiple Choice Hint Enable)
- Text String Questions (Text String Questions Enable, Text String Embedded Image Enable, Text String Hint Enabled)
- Sponsor Questions (Sponsor Questions Enable, Sponsor Multiple Choice Question Enable)
- Bonus Questions (Bonus Question Hint Points, Bonus Question Text Enable, Bonus Question Text Image Enable)
- Race Time (Start Race, End Race)

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine.
