### ISSUE TITLE
AppSettings Validation With RaceID

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#50]
Currently we have various validation according to the AppSettings. The same should be now done with the RaceID in context.

Some examples are but not limited to... 
1. Creation of Booth / Exhibitor
2. Creation of Categories
3. Creation of Difficulty Level
4. Choice of Text / Multiple Choice Questions and Bonus/Exhibitor Questions
5. Choice of Image Based Questions and Bonus/Exhibitor Questions
6. Number of Choice in Multiple Choice Questions

etc.

**Comment by debasishbanerjee** [comment]
Done.Test and Update

**Comment by krishnandusarkar** [comment]
Working Fine.
