### ISSUE TITLE
Race Screen

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#51]
1. Provide a button to Active/Deactivate a race. 
2. Activation and Deactivation should be done with a confirmation message from user.
3. On Activation of a particular race, all other active race should be deactivated i.e. at a single point of time only one race can be in active state.
4. Rename Splash Screen label to Entry Screen on Creation and Updation UI.

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine.
