### ISSUE TITLE
Dynamic Race Rules and Entry Screen

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#54]
1. A new screen should be introduced between Splash Screen and Home Screen such that the transition will now become Splash Screen (next) > Entry Screen (next) > Home Screen.

2. Create a new table named Race as per the notation below

```
RaceID - UUID - PRIMARY KEY
RaceName - VARCHAR (100) - NOT NULL
RaceRules - NVARCHAR(MAX) - NULL
EntryScreen - IMAGE/BLOG - NULL
ImageType - VARCHAR(100) - NULL
IsActive - BIT/BOOLEAN - NULL
CreatedOn - DATETIME - NOT NULL
CreatedBy - INT - NOT NULL
ModifiedOn - DATETIME - NULL
```

At a point of time only one race will be present in this table in Mobile DB which would be active.

3. The Entry Screen to be designed same as like in Splash Screen but the image should be fetched  from EntryScreen column from the above Race table.

4. RaceRules to be made dynamic and to be fetched from RaceRules column from the above mentioned Race table. Please note that, the data in RaceRules would be in HTML format, so it should be rendered as it is.

**Comment by snowbreeze** [comment]
Done
