### ISSUE TITLE
Race Excel Upload - New Column & Modified Logic For Text Questions

### ISSUE THREAD

**Issue by krishnandusarkar** [krishnandusarkar/SPE-v2#56]
1. On the excel they have given they will add a new column on L named "Picture / Video" where they will mark it as P OR V. So on getting P or V you have to mark that question as Picture or Video question and show it in summary so that they can later identify the row and upload the associated Picture or Video separately.

BTW they have praised the summary you came up with. :)

2. As I already said, they want the Question Error Summary to be displayed properly within the template we are using with a green Proceed button as we have in other pages.

3. They are not going to change the way they have given answers for text based questions. As the number of answer for text based questions is unlimited. So they will put it in Correct Answers column in comma separated format. So for text based questions, we have to explode the answers based on comma and put it as different rows in Answer table of which all the answer will be marked as correct answer.

**Comment by snowbreeze** [comment]
3. done

**Comment by snowbreeze** [comment]
@krishnandusarkar How to do 1 ?  @debasishbanerjee do last one

**Comment by debasishbanerjee** [comment]
Done
