### ISSUE TITLE
Adding an answer to a question

### ISSUE THREAD

**Issue by JaimeGomezSPE** [krishnandusarkar/SPE-v2#70]
In CHARACTERIZATION, EASY in the question "In tensile testing......"
I was trying to add an additional answer to the ones that were buck uploaded:
I typed:  'youngs modulus' and when pressing UPDATE, I received the following message:

error: Call to a member function execute() on a non-object in /var/www/html/v2/functions.php on line 2517

**Comment by krishnandusarkar** [comment]
@debasishbanerjee Can you please check this in urgent basis?

**Comment by debasishbanerjee** [comment]
Done
