### ISSUE TITLE
Results Statistics

### ISSUE THREAD

**Issue by JaimeGomezSPE** [krishnandusarkar/SPE-v2#83]
The column FIRST NAME is not needed as it is a repetition of the first column TEAM NAME.  Please eliminate this column from the results view

**Comment by krishnandusarkar** [comment]
@debasishbanerjee Can you please take off the FirstName from the SELECT list?

**Comment by debasishbanerjee** [comment]
Done

**Comment by krishnandusarkar** [comment]
Working Fine. Closing.
